import pygame

ROWS = 20
COLUMNS = 10
CELL_SIZE = 40
GAME_WIDTH = COLUMNS * CELL_SIZE
GAME_HEIGHT = ROWS * CELL_SIZE

LEFT_SIDEBAR_WIDTH = 200
RIGHT_SIDEBAR_WIDTH = 200

SCORE_HOLDER_DIVIDER = 0.7
SCORE_HEIGHT = SCORE_HOLDER_DIVIDER * GAME_HEIGHT
HOLDER_HEIGHT = (1 - SCORE_HOLDER_DIVIDER) * GAME_HEIGHT

WINDOW_PADDING = 20
WINDOW_WIDTH = GAME_WIDTH + LEFT_SIDEBAR_WIDTH + RIGHT_SIDEBAR_WIDTH + 4 * WINDOW_PADDING
WINDOW_HEIGHT = GAME_HEIGHT + WINDOW_PADDING * 2

COLORS = {
    'WINDOW_BACKGROUND': '#526375',
    'GAME_BACKGROUND': '#12151a',
    'HOLDER_BACKGROUND': '#8a7073',
    'SCORE_BACKGROUND': '#708a71',
    'SEQUENCE_BACKGROUND': '#89708a',
}
