
ROWS = 20
COLUMNS = 10
CELL_SIZE = 40
GAME_WIDTH = COLUMNS * CELL_SIZE
GAME_HEIGHT = ROWS * CELL_SIZE

LEFT_SIDEBAR_WIDTH = 200
RIGHT_SIDEBAR_WIDTH = 200

WINDOW_PADDING = 20
WINDOW_WIDTH = GAME_WIDTH + LEFT_SIDEBAR_WIDTH + RIGHT_SIDEBAR_WIDTH + 2 * WINDOW_PADDING
WINDOW_HEIGHT = GAME_HEIGHT + WINDOW_PADDING * 2
